Example webApp/Example webApp/Controllers/AdminController.cs
using BusinessLayer.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Example_webApp.Controllers
{
    [Authorize(Roles = "ADMIN")]
    public class AdminController : Controller
    {
        private readonly ILogger<AdminController> _logger;
        private IUserService _userService;

        public AdminController(ILogger<AdminController> logger, IUserService userServ)
        {
            _logger = logger;
            _userService = userServ;
        }

        public IActionResult Index()
        {
            return View(_userService.GetAllUsers());
        }

        [HttpPost]
        public IActionResult OnPost([FromBody] string data)
        {
            return Ok();
        }
    }
}

Example webApp/Example webApp/Controllers/GameController.cs
using BusinessLayer.Services;
using Example_webApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Example_webApp.Controllers
{
    public class GameController : Controller
    {

        private readonly ILogger<GameController> _logger;
        private IUserService _userService;

        public GameController(ILogger<GameController> logger, IUserService userServ)
        {
            _logger = logger;
            _userService = userServ;
        }

        [Authorize]
        public IActionResult Index()
        {
            return View("Index", HttpContext.User.Identity.Name);
        }

        [Authorize]
        public IActionResult Lobby()
        {
            return View();
        }

        [Authorize]
        public IActionResult Active()
        {
            return View();
        }

        public IActionResult Replay(int id)
        {
            return View(id);
        }

        [Authorize]
        public IActionResult History()
        {
            return View();
        }
    }
}

Example webApp/Example webApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Five In a Row</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body style="zoom: 75%">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3" >
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Five In a Row</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Chat">Chat</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Game" asp-action="Index">Game</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Game" asp-action="History">History</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="UserPanel">UserPanel</a>
                            </li>
                            @if (User.IsInRole("ADMIN"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="Index">AdminPanel</a>
                                </li>
                            }
                        }
                    </ul>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <span class="nav-item float-right">
                                <label for="logout" class="mr-2">@User.Identity.Name</label>
                                <a id="logout" class="text-white text-decoration-none" asp-area="Identity" asp-page="/Account/Logout">Logout</a>
                            </span>
                        }
                        else
                        {
                            <span class="nav-item float-right">
                                <a class="text-white text-decoration-none" asp-area="Identity" asp-page="/Account/Login">Login</a>
                            </span>
                        }
                </div>
            </div>
        </nav>
    </header>
    <div class="container page-body p-4 rounded shadow bg-light d-flex">
        <main role="main" class="pb-3 w-100">
            <div id="NotificationSpot">

            </div>
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Five In a Row - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/md5.min.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/microsoft-signalr/3.1.7/signalr.min.js"></script>
    <script>

		function AddNotification(notificationtext, alerttype = "success") {
            var element = $("#NotificationSpot");
            var alertDiv = document.createElement("div");
            alertDiv.setAttribute("class", "alert alert-" + alerttype + " alert-dismissible fade show");
            alertDiv.setAttribute("role", "alert");
            alertDiv.innerHTML = notificationtext;
            var dismissBtn = document.createElement("button");
            dismissBtn.type = "button";
            dismissBtn.setAttribute("class", "close");
            dismissBtn.setAttribute("data-dismiss", "alert");
            dismissBtn.setAttribute("aria-label", "Close");
            var btnSpan = document.createElement("span");
            btnSpan.setAttribute("aria-hidden", "true");
            btnSpan.innerHTML = "&times;";

            dismissBtn.appendChild(btnSpan);
            alertDiv.appendChild(dismissBtn);
            element.append(alertDiv);
            
			setTimeout(function (ele) {
				ele.setAttribute("hidden","");
			},5000,alertDiv);
        }

        const notifyConn = new signalR.HubConnectionBuilder()
            .withUrl("/notify/internal")
            .configureLogging(signalR.LogLevel.Information)
            .build();

        async function notifyConnStart() {
            try {
                await notifyConn.start();
                console.log("Notify Hub Connected");
            } catch (err) {
                console.log(err);
                setTimeout(notifyConnStart, 5000);
            }
        };

        notifyConn.onclose(notifyConnStart);

        notifyConn.on("AcceptNotification", (message) => {
            console.log("Notification recieved");
            AddNotification(message);
        });

        // Start the connection.
        notifyConnStart();
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>